# Generated by Django 2.0 on 2017-12-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0002_monthlyview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyview',
            name='match_id',
        ),
    ]
