# Generated by Django 2.0 on 2017-12-14 12:05

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('tier_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Tier')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.IntegerField(blank=True, null=True)),
                ('won', models.IntegerField(blank=True, null=True)),
                ('drawn', models.IntegerField(blank=True, null=True)),
                ('lost', models.IntegerField(blank=True, null=True)),
                ('points_for', models.IntegerField(blank=True, null=True)),
                ('points_against', models.IntegerField(blank=True, null=True)),
                ('bonus_points', models.IntegerField(blank=True, null=True)),
                ('total_points', models.IntegerField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugbyunion.Competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True)),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rugby_away_team', to='sports.Team')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugbyunion.Competition')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rugby_home_team', to='sports.Team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchScorecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugbyunion.Match')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_name', to='rugbyunion.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RugbyPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('second_name', models.CharField(blank=True, max_length=50)),
                ('domestic_teams', models.ManyToManyField(related_name='rugby_domestic_teams', to='sports.Team')),
                ('international_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rugby_international_team', to='sports.Team')),
            ],
        ),
        migrations.AddField(
            model_name='playerdetail',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugbyunion.RugbyPlayer'),
        ),
        migrations.AddField(
            model_name='playerdetail',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Team'),
        ),
        migrations.AddField(
            model_name='matchscorecard',
            name='squad',
            field=models.ManyToManyField(related_name='matchday_squad', to='rugbyunion.PlayerDetail'),
        ),
        migrations.AddField(
            model_name='matchscorecard',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Team'),
        ),
    ]
