# Generated by Django 2.0 on 2017-12-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='country_slug',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
