# Generated by Django 2.0 on 2017-12-29 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_team_country_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='country_slug',
        ),
    ]
