# Generated by Django 2.0 on 2017-12-30 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0002_auto_20171230_1217'),
        ('sports', '0003_remove_team_country_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='nation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nations.Country_Data'),
            preserve_default=False,
        ),
    ]
