# Generated by Django 2.0 on 2017-12-08 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('post_slug', models.SlugField(max_length=100, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=150, null=True)),
                ('body', models.TextField()),
                ('headline_image', models.FileField(blank=True, null=True, upload_to='')),
                ('post_image', models.FileField(blank=True, null=True, upload_to='')),
                ('posted', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_category', to='sports.Sport')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_team', to='sports.Team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_team', to='sports.Team')),
            ],
        ),
    ]
