# Generated by Django 2.0 on 2017-12-14 18:00

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20171210_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='team_a_country',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='team_b_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
