# Generated by Django 2.0 on 2017-12-14 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20171214_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='team_a_country',
        ),
        migrations.RemoveField(
            model_name='post',
            name='team_b_country',
        ),
    ]
