# Generated by Django 2.0 on 2017-12-27 17:15

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20171214_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('video', embed_video.fields.EmbedVideoField()),
                ('related_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Post')),
            ],
        ),
    ]
