# Generated by Django 2.0 on 2017-12-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20171227_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='videonews',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
