# Generated by Django 2.0 on 2017-12-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_videonews_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
