# Generated by Django 2.0 on 2017-12-30 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country_data',
            old_name='slug',
            new_name='country_slug',
        ),
    ]
